name: CI on Push

on:
  push:
    branches: [ "main" ] # This limits the workflow to only the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # Specifies the type of machine the job will run on

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4 # An action to download your repository's code

      - name: Run a simple echo command
        run: echo "Hello, world! This ran on a push event." # Runs a single-line script

      - name: Display current branch name
        run: echo "The job is running on branch ${{ github.ref_name }}"
